<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Microsoft.Build" Version="17.14.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WalletApp.Application\WalletApp.Application.csproj" />
    <ProjectReference Include="..\WalletApp.Domain\WalletApp.Domain.csproj" />
    <ProjectReference Include="..\WalletApp.Persistence\WalletApp.Persistence.csproj" />
  </ItemGroup>

</Project>
