USE WalletApplicationDB;
GO
CREATE TABLE [USER](
ID INT PRIMARY KEY IDENTITY(1,1),
EMAIL NVARCHAR(100),
PASSWORD NVARCHAR(50),
CREATED_DATE DATETIME DEFAULT GETDATE()
);

CREATE TABLE USERDETAÝL(
ID INT PRIMARY KEY IDENTITY(1,1),
AppUserId INT,
NAME NVARCHAR(50),
BIRTHDAY DATETIME,
OCCUPATÝON NVARCHAR(50),
PHONE_NUMBER INT

CONSTRAINT FK_USERDATEÝLS_USER FOREIGN KEY (AppUserId) REFERENCES [USER](ID)
)
